spring:
  data:
    web:
      pageable:
        default-page-size: 5
        size-parameter: size
        max-page-size: 10
        one-indexed-parameters: true
        page-parameter: page

  datasource:
    url: jdbc:h2:file:~/TESTDB;DATABASE_TO_UPPER=false #jdbc:h2:file:/JavaProjects/WeatherStationSpring/testH2/demo
    #jdbc:h2:file:~/TESTDB;DATABASE_TO_UPPER=false
    #jdbc:h2:file:/JavaProjects/WeatherStationSpring/testH2/demo
    username: sa
    password:
    driverClassName: org.h2.Driver
  jackson:
    serialization:
      indent_output: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: #create
              create-target: create_my_entity.sql
              create-source: metadata
    show-sql: true

  h2:
    console.enabled: true

  #datasource:
  #  # Tak narpawde to ponizej jest juz niepotrzebne jesli budujem compose'a
  #  url: jdbc:postgresql://localhost:5432/student
  #  password: student
  #  username: student
  #  driver-class-name: org.postgresql.Driver
  #jpa:
  #  properties:
  #    hibernate:
  #      jdbc:
  #        time_zone: UTC
  #      dialect: org.hibernate.dialect.PostgreSQLDialect
  #  generate-ddl: true
  #  hibernate:
  #    ddl-auto: create-drop
  #  open-in-view: false
  #  show-sql: true
  #messages:
  #  basename: text,exceptions
server:
  port: 8081
  error:
    path: /error
    whitelabel:
      enabled: false
logging:
  level:
    org:
      springframework:
        security: DEBUG
